#!/usr/bin/env bash
NAME="imagems"
VERSION="0.1.0"
DESCRIPTION="Image Micro-Service"
CANONICAL_NAME="imagemsv0"
CONF_DIR="/etc/imagems"
CONF_FILE="/etc/imagems/imagemsv0.conf.yml"
INSTALL_DIR="/usr/local/bin"
INSTALL_FILE="/usr/local/bin/imagemsv0"
UNIT_NAME="imagemsv0.service"
UNIT_FILE="/etc/systemd/system/imagemsv0.service"
DOCS_DIR="/etc/imagems/docs"
