// Code generated by protoc-gen-go.
// source: github.com/tomogoma/imagems/server/proto/image.proto
// DO NOT EDIT!

/*
Package image is a generated protocol buffer package.

It is generated from these files:
	github.com/tomogoma/imagems/server/proto/image.proto

It has these top-level messages:
	NewImageRequest
	NewImageResponse
*/
package image

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NewImageRequest struct {
	Token string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	Image []byte `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
}

func (m *NewImageRequest) Reset()                    { *m = NewImageRequest{} }
func (m *NewImageRequest) String() string            { return proto.CompactTextString(m) }
func (*NewImageRequest) ProtoMessage()               {}
func (*NewImageRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *NewImageRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *NewImageRequest) GetImage() []byte {
	if m != nil {
		return m.Image
	}
	return nil
}

type NewImageResponse struct {
	Id         string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Code       int32  `protobuf:"varint,2,opt,name=code" json:"code,omitempty"`
	ServerTime string `protobuf:"bytes,3,opt,name=serverTime" json:"serverTime,omitempty"`
	ImageURL   string `protobuf:"bytes,4,opt,name=imageURL" json:"imageURL,omitempty"`
	Detail     string `protobuf:"bytes,5,opt,name=detail" json:"detail,omitempty"`
}

func (m *NewImageResponse) Reset()                    { *m = NewImageResponse{} }
func (m *NewImageResponse) String() string            { return proto.CompactTextString(m) }
func (*NewImageResponse) ProtoMessage()               {}
func (*NewImageResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *NewImageResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *NewImageResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *NewImageResponse) GetServerTime() string {
	if m != nil {
		return m.ServerTime
	}
	return ""
}

func (m *NewImageResponse) GetImageURL() string {
	if m != nil {
		return m.ImageURL
	}
	return ""
}

func (m *NewImageResponse) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func init() {
	proto.RegisterType((*NewImageRequest)(nil), "NewImageRequest")
	proto.RegisterType((*NewImageResponse)(nil), "NewImageResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Publisher API

type Publisher interface {
	Publish(ctx context.Context, msg interface{}, opts ...client.PublishOption) error
}

type publisher struct {
	c     client.Client
	topic string
}

func (p *publisher) Publish(ctx context.Context, msg interface{}, opts ...client.PublishOption) error {
	return p.c.Publish(ctx, p.c.NewPublication(p.topic, msg), opts...)
}

func NewPublisher(topic string, c client.Client) Publisher {
	if c == nil {
		c = client.NewClient()
	}
	return &publisher{c, topic}
}

// Subscriber API

func RegisterSubscriber(topic string, s server.Server, h interface{}, opts ...server.SubscriberOption) error {
	return s.Subscribe(s.NewSubscriber(topic, h, opts...))
}

// Client API for Image service

type ImageClient interface {
	NewImage(ctx context.Context, in *NewImageRequest, opts ...client.CallOption) (*NewImageResponse, error)
}

type imageClient struct {
	c           client.Client
	serviceName string
}

func NewImageClient(serviceName string, c client.Client) ImageClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "image"
	}
	return &imageClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *imageClient) NewImage(ctx context.Context, in *NewImageRequest, opts ...client.CallOption) (*NewImageResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Image.NewImage", in)
	out := new(NewImageResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Image service

type ImageHandler interface {
	NewImage(context.Context, *NewImageRequest, *NewImageResponse) error
}

func RegisterImageHandler(s server.Server, hdlr ImageHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Image{hdlr}, opts...))
}

type Image struct {
	ImageHandler
}

func (h *Image) NewImage(ctx context.Context, in *NewImageRequest, out *NewImageResponse) error {
	return h.ImageHandler.NewImage(ctx, in, out)
}

func init() {
	proto.RegisterFile("github.com/tomogoma/imagems/server/proto/image.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 233 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x5c, 0x90, 0xcd, 0x4a, 0x03, 0x31,
	0x10, 0xc7, 0xcd, 0xda, 0x2d, 0xed, 0x20, 0x5a, 0x07, 0x91, 0xd0, 0x83, 0x2c, 0x7b, 0xda, 0xd3,
	0x06, 0x3f, 0x4e, 0x82, 0x0f, 0x20, 0x88, 0x87, 0xa0, 0x0f, 0xb0, 0x6d, 0x86, 0x35, 0x68, 0x3a,
	0x75, 0x93, 0xea, 0x3b, 0xf8, 0xd4, 0xd2, 0x49, 0xfd, 0xa0, 0xb7, 0xf9, 0xff, 0x86, 0x7f, 0xf2,
	0x4b, 0xe0, 0xa6, 0xf7, 0xe9, 0x65, 0xb3, 0x68, 0x97, 0x1c, 0x4c, 0xe2, 0xc0, 0x3d, 0x87, 0xce,
	0xf8, 0xd0, 0xf5, 0x14, 0xa2, 0x89, 0x34, 0x7c, 0xd0, 0x60, 0xd6, 0x03, 0x27, 0xce, 0xb0, 0x95,
	0xb9, 0xbe, 0x83, 0x93, 0x47, 0xfa, 0xbc, 0xdf, 0x12, 0x4b, 0xef, 0x1b, 0x8a, 0x09, 0xcf, 0xa0,
	0x4c, 0xfc, 0x4a, 0x2b, 0xad, 0x2a, 0xd5, 0x4c, 0x6d, 0x0e, 0x5b, 0x2a, 0x3d, 0x7d, 0x58, 0xa9,
	0xe6, 0xc8, 0xe6, 0x50, 0x7f, 0x29, 0x98, 0xfd, 0xf5, 0xe3, 0x9a, 0x57, 0x91, 0xf0, 0x18, 0x0a,
	0xef, 0x76, 0xed, 0xc2, 0x3b, 0x44, 0x18, 0x2d, 0xd9, 0x91, 0x2e, 0x2a, 0xd5, 0x94, 0x56, 0x66,
	0xbc, 0x00, 0xc8, 0x4e, 0x4f, 0x3e, 0xe4, 0x33, 0xa7, 0xf6, 0x1f, 0xc1, 0x39, 0x4c, 0xe4, 0x86,
	0x67, 0xfb, 0xa0, 0x47, 0xb2, 0xfd, 0xcd, 0x78, 0x0e, 0x63, 0x47, 0xa9, 0xf3, 0x6f, 0xba, 0x94,
	0xcd, 0x2e, 0x5d, 0xdd, 0x42, 0x29, 0x22, 0x78, 0x09, 0x93, 0x1f, 0x29, 0x9c, 0xb5, 0x7b, 0xef,
	0x9b, 0x9f, 0xb6, 0xfb, 0xc6, 0xf5, 0xc1, 0x62, 0x2c, 0xdf, 0x71, 0xfd, 0x1d, 0x00, 0x00, 0xff,
	0xff, 0x51, 0x0d, 0xca, 0x67, 0x46, 0x01, 0x00, 0x00,
}
